#!/bin/bash

# Start in root always
if [ ! -f .isroot ]
then
    echo "Must be run from root of project."; exit
fi

if [ "$1" = "--no-cache" ]
then
    cache_opt='--no-cache'
else
    cache_opt=''
fi

docker build $cache_opt -t ntaylor22/megatron:latest -f docker/Dockerfile .

# build dev version
head -n -2 docker/Dockerfile > docker/Dockerfile2
docker build $cache_opt -t ntaylor22/megatron-dev:latest -f docker/Dockerfile2 .
rm docker/Dockerfile2
